export { encrypt, decrypt } from './crypto'
export { ProviderRegistry } from './providers/registry'
export { DirectChannel } from './direct-channel'
export { checkBudget, addCost } from './budget'
export { extractFromFeed } from './tasks/extract-from-feed'
export { buildDeepDiveSystemPrompt, extractSuggestionsFromConversation } from './tasks/deep-dive'
export { FeedExtractionResultSchema } from './tasks/schemas'
export { buildGraphSummary } from './context/graph-summary'
export { loadPromptTemplate, clearTemplateCache } from './context/prompt-loader'
export { loadAspectTemplates, getAspectTemplate } from './context/aspect-templates'
export { findIslands, findGaps, findAgingNodes, collectTargets } from './tasks/scan-strategies'
export { runScan } from './tasks/run-scan'
export { startScheduler, stopScheduler, triggerManualScan } from './scheduler'
export type { AspectTemplate } from './context/aspect-templates'
export type { LLMProvider, LLMRequest, LLMResponse, ProviderConfig, ModelInfo, TokenUsage } from './providers/types'
export type { ExtractFromFeedInput, ExtractFromFeedOutput } from './tasks/extract-from-feed'
export type { DeepDiveContext } from './tasks/deep-dive'
export type { ScanTarget } from './tasks/scan-strategies'
export type { RunScanOptions, ScanResult } from './tasks/run-scan'

// Bridge
export { createBridgeTask, readBridgeResult, cancelBridgeTask, archiveBridgeTask } from './bridge/protocol'
export { BridgeWatcher } from './bridge/watcher'
export type { BridgeTaskFile } from './bridge/protocol'
